Mesh: Remove Data Order
ComputationalRadiationPhysics/openPMD-standard pull request #194
Opened 2018-04-24 13:51 UTC by ax3l

The data order for indices arises naturally from its flattened memory layout.
This also holds true for logical access to the data.

This affects the *base standard* attributes:
- `axisLabels`
- `gridSpacing`
- `gridGlobalOffset`
- `shape` of constant record components

and the *ED-PIC* extension attributes:
- `fieldBoundary`
- `particleBoundary`

*Implements issues:* #125 and #129

## Description

`dataOrder` is superfluous.

By defining 1D-flattened dimensions like `axisLabel` are ordered by fastest to slowest varying index one can omit `dataOrder`. Slowest to fastest varying index here only means the logical flattened memory layout that one assumes for this data format.

This is possible since one does not care *how* data was written but just about *how to label/name indices* when reading data. Naturally, one would increase from fastest to slowest dimension for all flattened descriptions over dimensions.

*Let's have a C-like to Fortran-like example*

A C-matrix `A[i,j,k]` is written with `i` index standing for `"x"`, `j` for `"y"` and `k` for `"z"`. The associated `axisLabels` is in the index order k-j-i (fastest is last) which is `("z", "y", "x")`.

A Fortran-reader reads this matrix as `M[a,b,c]` with the index order a-b-c (fastest is first). The `axisLabels` will assign `a` the label `"z"` , `b` the label `"y"` and the slowest varying index `c` an `"x"`. Index order and index label/name as as in C - hurray! :sparkles: 

## Affected Components

- `base`
- `EXT-ED-PIC`

## Logic Changes

Before one had to to write the index order of the writing code. We basically inverted C-like index orders during read when `dataOrder` was `C` to assign it to indices (in C again).

## Writer Changes

*How does this change affect data writers?*

Yes, C-writers need to invert now their order.
Fortran writers can just omit the `dataOrder` attribute now.

*Does this pull request change the interpretation of existing data writers?*

- [ ] `PIConGPU`: https://github.com/ComputationalRadiationPhysics/picongpu/...
- [ ] `Warp`: ...
- [ ] `FBPIC`: ...
- [ ] `openPMD-api` (upcoming): https://github.com/openPMD/openPMD-api/...

## Reader Changes

*How does this change affect data readers?*

Yes, *all readers* can now just label/name flattened dimension accesses to e.g. labels of indices in the same order as they access the indices of the mesh data (from fastest varying to slowest varying index).

*What would a reader need to change? Link implementation examples!*

- [ ] `openPMD-validator`: https://github.com/openPMD/openPMD-validator/...
- [ ] `openPMD-viewer`: https://github.com/openPMD/openPMD-viewer/...
- [ ] `yt`: https://github.com/yt-project/yt/...
- [ ] `VisIt`: https://github.com/openPMD/openPMD-visit-plugin
- [ ] `openPMD-api` (upcoming): https://github.com/openPMD/openPMD-api/...

## Data Converter

Mesh records that declare `dataOrder='C'` need to invert the attributes mentioned above.

The unused `dataOrder` attribute should be removed as well.

- [ ] https://github.com/openPMD/openPMD-converter/...

2018-04-24 14:50 UTC, anokfireball approved these changes
Simplifying the standard by integrating ```dataOrder``` into ```axisLabels``` improves understandability a lot. The user will have to be aware of this order, but now ambiguities that reference ```axisLabels``` (but not ```dataOrder```) are resolved.

2018-04-24 14:50 UTC, C0nsultant commented on STANDARD.md
> +    - advice to implementors: dimensions shall be ordered from fastest to
This clarification really makes the PR valuable.

2018-04-25 08:08 UTC, mccoys commented
If I understand correctly, C-order data will not be actually modified, but only the following attributes must have the order of their elements reversed ?

*    axisLabels
*   gridSpacing
*    gridGlobalOffset
*    shape of constant record components
*    fieldBoundary
*    particleBoundary

2018-04-25 08:44 UTC, ax3l commented
@mccoys from a C/C++/Python *writer* perspective (Smilei), yes just invert the order of those attributes when writing openPMD 2.0

2018-05-15 10:16 UTC, ax3l commented
There is also an alternative solution to this change, *ordering from slowest-to-fastest* varying index.

With that the existing Fortran files would need to change their index and we would generally have everything in C-like order. Due to the dominance of Py/C++ in our code bases, one could decide for that solution and have more consistency with e.g. numpy attributes >:-)

2018-05-15 14:57 UTC, RemiLehe requested changes

2018-05-15 14:57 UTC, RemiLehe commented on STANDARD.md
> +    - description: this attribute assigns for a matrix `A_{i,j,k}`
Could you clarify the meaning of `assigns for`, or maybe use some other phrasing?

2018-05-15 14:57 UTC, RemiLehe commented on STANDARD.md
> +    - description: this attribute assigns for a matrix `A_{i,j,k}`
One possibility is 
```
- description: human-reading labels for the `N` axes of the mesh, ordered *from fastest to slowest varying index when accessing the mesh contiguously (as 1D flattened logical memory)`

2018-05-15 15:21 UTC, ax3l commented on STANDARD.md
> +    - description: this attribute assigns for a matrix `A_{i,j,k}`
I think I wanted to write `assigns human-readible namings for the indices ... to a matrix ...`

2018-05-15 15:23 UTC, ax3l commented
@RemiLehe is it ok for you as well if I [change the order](https://github.com/openPMD/openPMD-standard/pull/194#issuecomment-389117002) to *slowest to fastest* varying index? :)

VC: ok with all.

2018-05-15 17:15 UTC, ax3l commented
all right, I updated the PR and PR description! :)

2018-05-15 17:20 UTC, ax3l commented on STANDARD.md
> +                              a matrix `A[i,j,k]` will have its last index
Fortran spells arrays `A(i,j,k)`

2018-05-15 17:20 UTC, ax3l commented on STANDARD.md
> +      - 2D `cartesian` mesh accessed in Fortran-like as `A[x,y]` will have `y` as
`A(x,y)`

2018-05-15 17:20 UTC, ax3l commented on STANDARD.md
> +      - `thetaMode` accessed Fortran-like `A[r,z]`, `axisLabels`: `("z", "r")`
`A(r,z)`

2018-05-16 04:14 UTC, RemiLehe approved these changes

2018-11-08 10:39 UTC, ax3l commented
@RemiLehe this PR should be ready to merge. Validator and Updater are up-to-date now :)

2018-11-13 14:53 UTC, merged